// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ISwitchboard
 * @notice Interface for Switchboard VRF on Monad Testnet
 * @dev Switchboard VRF Contract Address: 0xD3860E2C66cBd5c969Fa7343e6912Eff0416bA33
 */
interface ISwitchboard {
    /**
     * @notice Request randomness from Switchboard VRF
     * @return requestId The unique identifier for this randomness request
     */
    function requestRandomness() external payable returns (bytes32 requestId);

    /**
     * @notice Callback function that Switchboard calls with the random number
     * @param requestId The request ID that was returned from requestRandomness
     * @param randomness The random number generated by VRF
     */
    function fulfillRandomness(bytes32 requestId, uint256 randomness) external;
}
